spring:
  datasource:
    url: jdbc:sqlite:invoices.db
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

logging:
level:
  org.hibernate.SQL: DEBUG

company: 
  name: "Prénom Nom"
  siret: "000 000 000 00000"
  adress: "Adresse de l'entreprise"
  postalCode: "00000"
  city: "Ville"
  phone: "06 00 00 00 00"
  email: "contact@exemple.com"

