spring:
  datasource:
    url: jdbc:sqlite:invoices.db
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

logging:
level:
  org.hibernate.SQL: DEBUG
