spring:
  datasource:
    url: jdbc:sqlite:invoices.db
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

logging:
level:
  org.hibernate.SQL: DEBUG

company :
  name: "myname"
  siret: "SIRET : 15416565485"
  adress: "6 rue du coulommiers"
  postalCode: "06140"
  city: "town"
  phone: "0625"
  email: "seihnor@yahoo.com"